### ISSUE TITLE
TGAM1 vs. everything

### ISSUE THREAD

**Issue by 22chrs** [sixtyfive/tgam1#1]
Hallo !
Ich hoffe, dass ich dich auf diesem Wege erreiche. Du bist der einzige Mensch im ganzen Internet, der es geschafft hat das TGAM1 Modul scheinbar ohne Störung mit einen nicht Bluetooth device anzusteuern und zwar genau so wie ich das gerne machen würde.
Ich habe da ein richtig großes Problem, vor dem ich schon ein paar Monate sitze. Meinst du wir könnten uns in Leipzig (Hier steht Uni Leipzig :) mal auf eine halbe Stunde treffen? Ich studiere in Halle! 
Du würdest mir würdest mir mega unendlich viel weiterhelfen!
Grüße, Chris
PS: schreibe mir gerne hier: mail@chriswalter.org
Danke dir !!

**Comment by sixtyfive** [comment]
Hi Chris, leider stimmt "scheinbar ohne Störung" nicht. Was wir per MQTT extrahieren ist kein gutes EEG-Signal. Sobald ich das WiFi abschalte und mir die Daten per Serial hole, wird es besser. Habe ein wenig mit Abschirmung, etc. experimentiert, aber bis jetzt noch keine wirklich taugliche Lösung gefunden. Sorry...

**Comment by sixtyfive** [comment]
(No further activity...)
